export const tobaccos: string[] = [
  "マールボロ (Marlboro)",
  "キャメル (Camel)",
  "ウィンストン (Winston)",
  "レッキー (Lucky Strike)",
  "パラマウント (Parliament)",
  "バージニアスリムス (Virginia Slims)",
  "ハビタン (Habanos)",
  "ダビドフ (Davidoff)",
  "デュモーリエ (Dunhill)",
  "センサ (Sensa)",
  "ピーター・ステュイヴェスァント (Peter Stuyvesant)",
  "デュモン (Dumont)",
  "プッカ (Pukka)",
  "カメラ (Kamra)",
  "マビク (Mevius)",
  "ケント (Kent)",
  "パラリメント (Parliament)",
  "バンソン (Benson & Hedges)",
  "ポールモール (Pall Mall)",
  "デービッドオフ (Davidoff)",
  "シルクカット (Silk Cut)",
  "ボールダー (Boule d'or)",
  "バージニアゴールド (Virginia Gold)",
  "エクスポートA (Export A)",
  "デュモア (Dumaur)",
  "キンバリー (Kimberley)",
  "コンピオス (Compios)",
  "ディープブルー (Deep Blue)",
  "プレミア (Premier)",
  "エグゼクティブ (Executive)",
];
